import "./globals.css";
import { inter } from "../../public/fonts/font";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.className} antialiased`}>
      <body className="">{children}</body>
    </html>
  );
}
